//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 05:09:40 PM CEST 
//


package com.example.demo.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GetMovieRequest }
     * 
     */
    public GetMovieRequest createGetMovieRequest() {
        return new GetMovieRequest();
    }

    /**
     * Create an instance of {@link GetMovieResponse }
     * 
     */
    public GetMovieResponse createGetMovieResponse() {
        return new GetMovieResponse();
    }

    /**
     * Create an instance of {@link Movie }
     * 
     */
    public Movie createMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link SetMovieRequest }
     * 
     */
    public SetMovieRequest createSetMovieRequest() {
        return new SetMovieRequest();
    }

    /**
     * Create an instance of {@link SetMovieResponse }
     * 
     */
    public SetMovieResponse createSetMovieResponse() {
        return new SetMovieResponse();
    }

    /**
     * Create an instance of {@link DeleteMovieRequest }
     * 
     */
    public DeleteMovieRequest createDeleteMovieRequest() {
        return new DeleteMovieRequest();
    }

    /**
     * Create an instance of {@link DeleteMovieResponse }
     * 
     */
    public DeleteMovieResponse createDeleteMovieResponse() {
        return new DeleteMovieResponse();
    }

    /**
     * Create an instance of {@link GetSeriesRequest }
     * 
     */
    public GetSeriesRequest createGetSeriesRequest() {
        return new GetSeriesRequest();
    }

    /**
     * Create an instance of {@link GetSeriesResponse }
     * 
     */
    public GetSeriesResponse createGetSeriesResponse() {
        return new GetSeriesResponse();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link SetSeriesRequest }
     * 
     */
    public SetSeriesRequest createSetSeriesRequest() {
        return new SetSeriesRequest();
    }

    /**
     * Create an instance of {@link SetSeriesResponse }
     * 
     */
    public SetSeriesResponse createSetSeriesResponse() {
        return new SetSeriesResponse();
    }

    /**
     * Create an instance of {@link DeleteSeriesRequest }
     * 
     */
    public DeleteSeriesRequest createDeleteSeriesRequest() {
        return new DeleteSeriesRequest();
    }

    /**
     * Create an instance of {@link DeleteSeriesResponse }
     * 
     */
    public DeleteSeriesResponse createDeleteSeriesResponse() {
        return new DeleteSeriesResponse();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link SetUserRequest }
     * 
     */
    public SetUserRequest createSetUserRequest() {
        return new SetUserRequest();
    }

    /**
     * Create an instance of {@link SetUserResponse }
     * 
     */
    public SetUserResponse createSetUserResponse() {
        return new SetUserResponse();
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link Episode }
     * 
     */
    public Episode createEpisode() {
        return new Episode();
    }

    /**
     * Create an instance of {@link Season }
     * 
     */
    public Season createSeason() {
        return new Season();
    }

    /**
     * Create an instance of {@link User.CreatedSeries }
     * 
     */
    public User.CreatedSeries createUserCreatedSeries() {
        return new User.CreatedSeries();
    }

}
